name: Comment PR

on:
  # Triggers the workflow on push or pull request events but only for the main/master branch
  push:
    branches: [ main, master ]
jobs:
  comment-pr:
    name: Comment PR
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        id: comment_pr
        uses: htec-infra/gha-utils/utils/comment-pr@VERSION
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"