name: 'Container operations'
description: 'Publish comment on PR'

inputs:
  token:
    description: 'Github access token'
    required: true
  repo_summary:
    description: 'Repo summary'
    required: false


runs:
  using: "composite"
  steps:
    - id: repo_data
      shell: bash
      run: ${{ github.action_path }}/../../scripts/repo_data.sh
    - name: Comment PR
      uses: actions/github-script@v5
      env:
        # REPO_SUMMARY: ${{ inputs.repo_summary || steps.repo_data.outputs.REPO_SUMMARY }}
        REPO_SUMMARY: "test"
      with:
        github-token: ${{ inputs.token }}
        REPO_SUMMARY: ${{ inputs.repo_summary || steps.repo_data.outputs.REPO_SUMMARY }}
        script: |
          const { GITHUB_ACTION_PATH } = process.env
          const script = require(`${GITHUB_ACTION_PATH}/../../scripts/comment_pr.js`)
          await script({github, context})